### ISSUE TITLE
TypeError: self.server.inject is not a function

### ISSUE THREAD

**Issue by jerome724** [klokoy/hapi-test#8]
Hey!

I'm pretty new to mocha and testing.

My code:

```js
'use strict';
const hapiTest = require('hapi-test');
const assert = require('assert');
const server = require('./index');

it('it should return statusCode 200', done => {
  hapiTest({ server: server })
  .get('/test')
  .assert(200, done);
});
```

When i'm running the test with mocha i'm getting an ``TypeError``

```
λ mocha


(node:2808) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
  1) it should return statusCode 200

  0 passing (19ms)
  1 failing

  1)  it should return statusCode 200:
     TypeError: self.server.inject is not a function
      at handleRequest (node_modules\hapi-test\src\hapiTest.js:207:25)
      at node_modules\hapi-test\src\hapiTest.js:232:9
      at HapiTest._init (node_modules\hapi-test\src\hapiTest.js:55:9)
      at HapiTest.end (node_modules\hapi-test\src\hapiTest.js:195:10)
      at HapiTest.assert (node_modules\hapi-test\src\hapiTest.js:155:18)
      at Context.done (test.js:9:4)
```

When i leave the ``hapiTest(options)`` blank, eg ``hapiTest()`` then i'm getting the following ``TypeError``:

```
λ mocha


(node:2032) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
  1) it should return statusCode 200

  0 passing (19ms)
  1 failing

  1)  it should return statusCode 200:
     TypeError: Cannot read property 'server' of undefined
      at new HapiTest (node_modules\hapi-test\src\hapiTest.js:13:16)
      at module.exports (node_modules\hapi-test\src\hapiTest.js:7:12)
      at Context.done (test.js:7:3)
```

So yea, i don't really know where the problem is in my spaghetti code.

**Comment by klokoy** [comment]
What is in your `index`file? You have to provide an instance of a server or a plugin to hapiTest. Check what your `index` file exports? 

Remember that if you use the server directly you need to get the server instance from it. I.e.  update your test to:

```
'use strict';
const hapiTest = require('hapi-test');
const assert = require('assert');
const server = require('./index');

it('it should return statusCode 200', done => {
  hapiTest({ server: server.server })   // <==  get server instance
  .get('/test')
  .assert(200, done);
});
```


An index file like this will not work:  It does not export anything.

```
const Hapi = require('hapi');

// Create a server with a host and port
const server = new Hapi.Server();
server.connection({ 
    host: 'localhost', 
    port: 8000 
});

// Add the route
server.route({
    method: 'GET',
    path:'/hello', 
    handler: function (request, reply) {

        return reply('hello world');
    }
});

Start the server
server.start((err) => {
    if (err) {
        throw err;
    }
    console.log('Server running at:', server.info.uri);
});
```

But this should work (I just exported the server).  

```
const Hapi = require('hapi');

// Create a server with a host and port
const server = new Hapi.Server();
server.connection({ 
    host: 'localhost', 
    port: 8000 
});

// Add the route
server.route({
    method: 'GET',
    path:'/hello', 
    handler: function (request, reply) {

        return reply('hello world');
    }
});

Start the server
server.start((err) => {
    if (err) {
        throw err;
    }
    console.log('Server running at:', server.info.uri);
});

module.exports.server = server;
```

**Comment by jerome724** [comment]
Yep.. sorry that was my mistake, totally forgot that i'm exporting the server as following:

server.js:
```js
module.exports = Server;
```

index.js:
```js
module.exports = {
Server: require('./server')
};
```

and in my app.js:
```js
const {
Server
} = require('./server');
```

Closing because was my own fault.

Thanks!

**Comment by klokoy** [comment]
No problem, glad you solved it...
